--- uvccapture-0.5/Makefile     2008-08-01 04:26:18.000000000 +0200
+++ Makefile    2009-03-09 10:46:22.000000000 +0100
@@ -1,13 +1,13 @@
-CC=gcc
+#CC=gcc
 CPP=g++
 APP_BINARY=uvccapture
-VERSION = 0.4
-PREFIX=/usr/local/bin
+VERSION = 0.5
+PREFIX=/usr/bin
 
 WARNINGS = -Wall
 
 
-CFLAGS = -std=gnu99 -O2 -DLINUX -DVERSION=\"$(VERSION)\" $(WARNINGS)
+CFLAGS += -std=gnu99 -O2 -DLINUX -DVERSION=\"$(VERSION)\" $(WARNINGS)
 CPPFLAGS = $(CFLAGS)
 
 OBJECTS= uvccapture.o v4l2uvc.o
 
