#!/bin/sh
FOREVER=0
SECONDS=2

python /usr/bin/touchtokillslideshow.py &

while [ $FOREVER -lt 1 ]; do

fbv -d -i 30 /home/root/images/800x480/horizontal/1280px-Flower_jtca001.jpg
sleep $SECONDS 
fbv -d -i 30 /home/root/images/800x480/horizontal/339146368_5e2ec1b1f5_o.jpg
sleep $SECONDS
fbv -d -i 30 /home/root/images/800x480/horizontal/3946279121_e3de277f3d_o.jpg 
sleep $SECONDS
fbv -d -i 30 /home/root/images/800x480/horizontal/416016_priroda_kanon_1680x1050_\(www.GdeFon.ru\).jpg
sleep $SECONDS
fbv -d -i 30 /home/root/images/800x480/horizontal/4547494619_7dc2628d09_o.jpg
sleep $SECONDS
fbv -d -i 30 /home/root/images/800x480/horizontal/5040077450_d4abe28445_o.jpg
sleep $SECONDS
fbv -d -i 30 /home/root/images/800x480/horizontal/5187385512_f0d42cff3e_o.jpg
sleep $SECONDS
fbv -d -i 30 /home/root/images/800x480/horizontal/6963572323_f93c4f68e8_o.jpg
sleep $SECONDS
fbv -d -i 30 /home/root/images/800x480/horizontal/7866099788_d57a0ecd6c_o.jpg
sleep $SECONDS
fbv -d -i 30 /home/root/images/800x480/horizontal/8544727431_dc23298173_o.jpg
sleep $SECONDS
fbv -d -i 30 /home/root/images/800x480/horizontal/A_white_water_lily_in_a_pond_-_03.jpg
sleep $SECONDS
fbv -d -i 30 /home/root/images/800x480/horizontal/Dendrobates_azureus_\(Dendrobates_tinctorius\)_Edit.jpg
sleep $SECONDS
fbv -d -i 30 /home/root/images/800x480/horizontal/The-best-top-desktop-space-wallpapers-0p-hd-space-wallpaper-planets.jpg
sleep $SECONDS
fbv -d -i 30 /home/root/images/800x480/horizontal/Xeroxidated_by_starfantazy.jpg
sleep $SECONDS
fbv -d -i 30 /home/root/images/800x480/horizontal/colibri.71212.jpg
sleep $SECONDS
fbv -d -i 30 /home/root/images/800x480/horizontal/cool_flower-wide.jpg
sleep $SECONDS
fbv -d -i 30 /home/root/images/800x480/horizontal/sunrise_at_brigde_by_panjirelawan-d5cttd6.jpg
sleep $SECONDS
fbv -d -i 30 /home/root/images/800x480/horizontal/yellow-and-silver-fish.jpg
sleep $SECONDS

done
